### ISSUE TITLE
Task list to improve site!

### ISSUE THREAD

**Issue by pyrrhamide** [pyrrhamide/mission-website#3]
- [x] delete most examples and templates left from Academic.
- [x] insert a Table of Content at the beginning of each post.
- [x] finish CV
- [x] div notes (see Alison Hill and Desirée De Leon)
- [x] HTTPS thing: do I keep it or not? I'm annoyed by how often my SSL certificate isn't recognised.
- [x] translate slugs in French for URL/SEO stuff (add `slug: a-propos` in `about.md` file?)
- [ ] dates dates dates
- [x] shortcode for update stuff (green would be a nice colour 😬 )

**Comment by pyrrhamide** [comment]
note to self: stop pushing so often. edit, preview from RStudio, commit, but stop your compulsive need to push to GH!!!!

**Comment by pyrrhamide** [comment]
deleted the `_redirects` file pushing to HTTPS (honestly, this SSL thing was annoying), but might actually put it back on to redirect netlify URL to rbind. idk.

**Comment by pyrrhamide** [comment]
re: TOC. I did it. `layouts/shortcodes/table_of_contents.html`
```
<h3>Contents</h3>

<div class="toc">
    {{ .Page.TableOfContents }}
</div>
```

add `{{< table_of_contents >}}` in (R)Markdown file, where I want the TOC to be. in `assets/scss/custom.scss`:
```
#TableOfContents li a, .toc-top li a {
	padding: .125rem 1rem;
	font-size: .9rem;
  text-transform: inherit;
  text-align: left;
	color: #1a162d99;
}

#TableOfContents {
  border-left: 1px solid #172A3A;
  padding-top: 0.5rem;
  padding-bottom: 0rem;
  margin-top: 1rem; /* ecart image featured TOC */
  margin-bottom: 2rem; /* ecart TOC premier para */
}
```

great stuff. BUT THERE IS A BUT: Idk how to handle translation h3 header "Contents" to French (if I add `.en.html`, no bueno). as long as I can't find out how to do it, I'll forgo TOCs.

**Comment by pyrrhamide** [comment]
re:TOC changes
to `table_of_contents.html` -> delete `<h3>Contents</h3>`

to `custom.scss` -> add
```
#TableOfContents:before{
    content: "Outline";
    font-family: 'Raleway', sans-serif!important;
    font-weight: bold;
    font-size: 19px;
    padding-left: 1rem;
}
```

still issue of TOC header name that I can't apply to French side of website. *le sigh*

**Comment by pyrrhamide** [comment]
re: div tips & TOC. the easiest answer was [SHORTCODES](https://iphysresearch.github.io/blog/post/writting-markdown/) (_smh_...).

* for div tips: `{{% callout warning %}} ... {{% /callout %}}`
* for TOC: `{{% toc %}}`
